config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  resources :artists do
    resources :songs, only: [:show, :new, :create, :edit, :update, :destroy]
    # get '/songs/:artist_id/:song_id', to: 'songs#show', as: 'artist_song' 
    # get '/artists/:artist_id', to: 'artists#show', as: 'artist'
    # saving these for after the project review since i don't want to use restful urls. those are dumb.
  end
  resources :songs, only: [:index, :new, :create]
  resources :genres, only: [:index, :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users', to: 'users#index', as: 'users'
  get '/users/username', to: 'users#username', as: 'username'
  patch '/users/:id', to: 'users#create_username'
  post '/users', to: 'users#create'
  get '/users/:username', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:username/toggle', to: 'users#toggle_party', as: 'toggle_party'
  get '/search', to: 'search#show', as: 'search_page'
  post '/usersongs', to: 'user_songs#create', as: 'add_song'
  post '/usersongs/game', to: 'user_songs#add_game', as: 'add_game' 
  patch '/usersongs', to: 'user_songs#rate_song', as: 'rate_song'
  delete '/usersongs', to: 'user_songs#destroy', as: 'remove_song'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'
  namespace :party do
    root 'static#party'
    get '/:username/playlist', to: 'playlists#index', as: 'playlist'
    get '/:username', to: 'hosts#show'
    get '/:username/playlist/edit', to: 'playlists#edit'
    get '/:username/history', to: 'histories#show', as: 'user_history'
    patch '/:username', to: 'hosts#update'
    delete '/:username', to: 'hosts#destroy'
    get '/:username/guests', to: 'guests#index', as: 'guests_home'
    get '/:username/guests/new', to: 'guests#new', as: 'guests_add_song'
    delete '/guests', to: 'guests#destroy', as: 'clear_song'
    get '/histories', to: 'histories#index'
    get '/:username/add-song', to: 'guests#new'
    post '/:username', to: 'guests#create'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def show
        if params[:search].blank?  
            flash[:alert] = "Search field empty!"
            redirect_back(fallback_location: songs_path)
        else  
            @search = params[:search]
            @results = Song.joins(:artist).search(params[:search]).order(:name).page(params[:page]).per(10)
        end  
    end

    private

    def search_params
        params.require[:search]
    end
end

app/views/search/_search.html.erb
<%= form_tag(search_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>

<h3>Search Result</h3>  
    <% @results.each do |result| %>  
        <%= result.store.name %> <%= result.name %><br>  
    <% end %>

app/views/search/show.html.erb
<h1>Search for Songs</h1>
<h3>Search Results for "<%= @search %>" - <%= @results.count %> songs found. </h3>  

<%= page_entries_info @results %>
<%= paginate(@results) %>
<% @results.each do |result| %>

<div class="card-group">
  <div class="card">
    <%= display_album_art(result) %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to result.full_title, artist_song_path(result.artist, result) %></h5>
      <p class="card-text"><%= link_to result.artist.full_name, artist_path(result.artist) %></p>
    </div>
  </div>
<% end %>