config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  resources :artists do
    resources :songs, only: [:show, :new, :create, :edit, :update, :destroy]
    # get '/songs/:artist_id/:song_id', to: 'songs#show', as: 'artist_song' 
    # get '/artists/:artist_id', to: 'artists#show', as: 'artist'
    # saving these for after the project review since i don't want to use restful urls. those are dumb.
  end
  resources :songs, only: [:index, :new, :create]
  resources :genres, only: [:index, :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users', to: 'users#index', as: 'users'
  get '/users/username', to: 'users#username', as: 'username'
  patch '/users/:id', to: 'users#create_username'
  post '/users', to: 'users#create'
  get '/users/:username', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:username/toggle', to: 'users#toggle_party', as: 'toggle_party'
  get '/search', to: 'search#show', as: 'search_page'
  post '/usersongs', to: 'user_songs#create', as: 'add_song'
  post '/usersongs/game', to: 'user_songs#add_game', as: 'add_game' 
  patch '/usersongs', to: 'user_songs#rate_song', as: 'rate_song'
  delete '/usersongs', to: 'user_songs#destroy', as: 'remove_song'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'
  namespace :party do
    root 'static#party'
    get '/:username/playlist', to: 'playlists#index', as: 'playlist'
    get '/:username', to: 'hosts#show'
    get '/:username/playlist/edit', to: 'playlists#edit'
    get '/:username/history', to: 'histories#show', as: 'user_history'
    patch '/:username', to: 'hosts#update'
    delete '/:username', to: 'hosts#destroy'
    get '/:username/guests', to: 'guests#index', as: 'guests_home'
    get '/:username/guests/new', to: 'guests#new', as: 'guests_add_song'
    delete '/guests', to: 'guests#destroy', as: 'clear_song'
    get '/histories', to: 'histories#index'
    get '/:username/add-song', to: 'guests#new'
    post '/:username', to: 'guests#create'
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :artist
    belongs_to :genre
    has_many :user_songs, dependent: :destroy
    has_many :users, through: :user_songs
    
    accepts_nested_attributes_for :artist

    validates_presence_of :name
    validates_presence_of :artist_id
    validates :year, numericality: { greater_than: 1954, less_than_or_equal_to: Proc.new {|record| Date.current.year } }
    validates :vocal_parts, presence: true, inclusion: { in: 0..3, message: "Number of Vocal Parts must be between 0 and 3" }
    
    before_create :check_name_for_article, :check_artist_name_for_article, :set_song_source_and_availability
    after_create :get_xbox_link, :get_psn_link, :get_spotify_id

    scope :owned, ->(user) { left_outer_joins(:users).where(user_songs: { user_id: user.id } ) }
    scope :unowned, ->(user) { where.not(id: owned(user)) }

    
    def full_title
        if self.article != ""
            "#{self.article}" + " " + "#{self.name}"
        else
            self.name
        end
    end

    def artist_name
        self.try(:artist).try(:name)
    end

    def length_in_minutes
        Time.at(self.duration / 1000).strftime("%M:%S")
    end
    
    def harmony_parts?
        if self.vocal_parts > 1
            "Yes, this song has #{self.vocal_parts} vocal parts"
        elsif self.vocal_parts == 1
            "Solo Only"
        else
            "This song does not have vocals"
        end
    end

    def is_song_cover?
        if self.cover == true
            "As made famous by "
        end
    end

    def has_ratings?
        !UserSong.where(song_id: self.id).average(:rating).nil?
    end

    def primary_source
        case self.source
            when 1
                "Rock Band 1"
            when 2
                "Rock Band 2"
            when 3
                "Rock Band 3"
            when 4
                "Rock Band 4"
            when 21 
                "Rock Band Track Pack: Vol. 1"
            when 22 
                "Rock Band Track Pack: Vol. 2"
            when 23 
                "AC/DC Live: Rock Band Track Pack"
            when 24 
                "Rock Band Track Pack: Classic Rock"
            when 25 
                "Rock Band Country Track Pack"
            when 26 
                "Rock Band Metal Track Pack"
            when 27 
                "Rock Band Country Track Pack 2"
            when 51
                "LEGO: Rock Band"
            when 52
                "Green Day: Rock Band"
            when 53
                "Rock Band Blitz"    
            when 99
                "Rock Band Network"
            else
                "Downloadable Content"
        end
    end

    def artist_name=(name)
        name.check_name_for_article
        self.artist = Artist.find_or_create_by(name: name)
    end


    def check_name_for_article
        if self.name[0..2] == "The"
            self.article = "The"
            self.name = self.name.delete_prefix("The ")
        elsif self.name[0..1] == "A "
            self.article = "A"
            self.name = self.name.delete_prefix("A ")
        elsif self.name[0] == "("
            self.article = "("
            self.name = self.name.delete_prefix("(")
        elsif self.name[0..2] == "..." #dammit metallica
            self.article = "..."
            self.name = self.name.delete_prefix("...")
        else
            self.article = ""
        end
    end

    def check_artist_name_for_article
        if self.artist.name[0..2] == "The"
            self.artist.article = "The"
            self.artist.name = self.artist.delete_prefix("The ")
        elsif self.artist.name[0..1] == "A "
            self.artist.article = "A"
            self.artist.name = self.artist.name.delete_prefix("A ")
        else
            self.artist.article = ""
        end
    end

    def set_song_source_and_availability
        self.source = 100
        self.availability = 4
    end
    
    def get_xbox_link
        m = Mechanize.new
        m.user_agent_alias = 'Mac Safari'
        page = m.get("https://www.google.com")
        google_form = page.form('f') 
        google_form.q = "microsoft.com/en-us/ \"#{self.name}\" \"#{self.artist.name}\" -rocksmith -\"dance central\""
        page = m.submit(google_form)
        pp = page.links_with :href => /microsoft.com\/en-us\/p/
        if pp.first
            self.xbox_link = pp.first.href[32..-1].gsub(/\&sa(.*)/, "")
        else
            self.xbox_link = "Scrape Error"
        end
        self.save
    end

    def get_psn_link
        m = Mechanize.new
        m.user_agent_alias = 'Mac Safari'
        page = m.get("https://www.google.com")
        google_form = page.form('f') 
        google_form.q = "store.playstation.com/en-us \"#{self.name}\" \"#{self.artist.name}\" -rocksmith"
        page = m.submit(google_form)
        pp = page.links_with :href => /store.playstation.com\/en-us\/product/
        if pp.first
            self.psn_link = pp.first.href[36..-1].gsub(/\&sa(.*)/, "").gsub(/\%3(.*)/, "")
        else
            self.psn_link = "Scrape Error"
        end
        self.save
    end

    def get_spotify_id
        RSpotify.authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"])
        tracks = RSpotify::Track.search("#{self.full_title} artist:#{self.artist.full_name}")
        if !tracks.empty?
            if tracks.first.artists.first.name == self.artist.full_name
                self.spotify_id = tracks.first.id
            elsif tracks.second.artists.first.name == self.artist.full_name
                self.spotify_id = tracks.second.id
            elsif tracks.third.artists.first.name == self.artist.full_name
                self.spotify_id = tracks.third.id
            else
                self.spotify_id = "Find It Yourself"
            end
        else
            self.spotify_id = "Find It Yourself"
        end
        self.save
    end

    def self.search(search)  
        where("lower(artists.name) LIKE :search OR lower(songs.name) LIKE :search", search: "%#{search.downcase}%").distinct   
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :set_song, only: [:show, :edit, :update, :destroy]
    before_action :message_if_not_admin, only: [:new, :create, :edit, :update, :destroy]
    
    def index
        @songs = Song.order('LOWER(name)')
        if params[:view]        
            if params[:view] == "owned"
                @songs = @songs.owned(current_user).page(params[:page])
            elsif params[:view] == "unowned"
                @songs = @songs.unowned(current_user).page(params[:page])
            else 
                @songs = Song.order('LOWER(name)')
            end
        end
        if params[:sort] == "artist" || params[:sort] == "genre"
            @songs = Song.joins(:"#{params[:sort]}").order("#{params[:sort]}s.name").page(params[:page])
        else
            @songs = @songs.page(params[:page])
        end
        if current_user
            @user_song = current_user.user_songs.build(user_id: current_user.id)
        end
    end

    def show
        @user_song = UserSong.where(song_id: @song.id)
    end

    def new
        if params[:artist_id]
            @song = Song.new
            @song.artist = Artist.friendly.find(params[:artist_id])
            @song.build_genre
        else
            @song = Song.new
            # params[:artist_id] ? @song.artist = Artist.friendly.find(params[:artist_id]) : @song.build_artist
            @song.build_artist
            @song.build_genre
        end
    end

    def create
        @song = Song.new(song_params)
        if params[:song][:artist_id].empty?
            @song.artist = Artist.find_or_create_by(name: params[:song][:artist_attributes][:name])
        end
        if @song.valid?
            @song.save
            flash[:notice] = "#{@song.full_title} has been successfully added to database!"
            redirect_to artist_song_path(@song.artist, @song)
        else
            @song.destroy
            render 'songs/new'
        end
    end

    def edit
        @artist = @song.artist
    end

    def update
        if @song.update(update_song_params)
            flash[:notice] = "#{@song.full_title} has been successfully updated"
            redirect_to artist_song_path(@song.artist, @song)
        else
            render 'songs/edit'
        end
    end

    def destroy
        if user_is_admin
            @song.destroy
            redirect_to songs_path
        else
            flash[:notice] = "Only an admin can delete songs"
            render 'songs'
        end
    end

    private
    
    def set_song
        @song = Song.friendly.find(params[:id])
    end

    def song_params
        params.require(:song).permit(:name, :artist_id, :genre_id, :year, :vocal_parts, :artist_attributes => [:name])#, :genre_attributes => [:name])
    end

    def update_song_params
        params.require(:song).permit(:name, :artist_id, :genre_id, :year, :vocal_parts)
    end

end

app/helpers/songs_helper.rb
module SongsHelper
    
    def render_game_button(source, source_id)
        button_to "#{source}", action: "add_game", controller: "user_songs", params: { source: source_id }
    end

    def game_already_in_collection?(source_id)
        current_user.songs.where(source: source_id).size  == Song.where(source: source_id).size
    end

    def edit_button_for_admin
        if current_user == User.find(1)
            link_to "Edit Song Details", edit_artist_song_path(@song.artist, @song)
        end
    end

    def new_button_for_admin
        if current_user == User.find(1)
            link_to "Create New Song", new_artist_song_path(@artist, @artist.songs.build)
        end
    end

    def destroy_button_for_admin
        if current_user == User.find(1)
            link_to "Delete Song", artist_song_path(@song.artist, @song), method: :delete
        end
    end

    def render_xbox_link
        if self.id > 2795
            link_to "Buy this song on Xbox Live Marketplace", "https://www.microsoft.com#{self.xbox_link}"
        else
            link_to "Buy this song on Xbox Live Marketplace", "rbdb/#{self.xbox_link}"
        end
    end

    def render_psn_link
        if self.id > 2795
            link_to "Buy this song on Playstation Store", "https://www.microsoft.com#{self.psn_link}"
        else
            link_to "Buy this song on Playstation Store", "rbdb/#{self.psn_link}"
        end
    end
    
    def display_own_rating
        if !@user_song.find_by(user_id: current_user.id, song_id: @song.id).rating.nil?
            content_tag(:p, "Your Rating: #{@user_song.find_by(user_id: current_user.id, song_id: @song.id).rating}")
        else
            content_tag(:p, "You have not rated this song yet.")
        end
    end

end

app/views/songs/_form.html.erb
    <%= render 'layouts/errors', object: @song %>

    <%= f.label "Song Name" %><br>
    <%= f.text_field :name %><br>
    <%= f.label "Artists in Database" %><br>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, { prompt: "Select Artist", selected: @song.artist ? @song.artist.id : nil } %><br>
    <% if current_page?(new_song_path) %>
        <%= f.label "If artist doesn't exist yet, create it here!" %>   
        <%= f.fields_for :artist, @song.build_artist do |artist_fields| %>
            <%= artist_fields.label "New Artist Name" %>
            <%= artist_fields.text_field :name %><br>
        <% end %>
    <% end %>
    <%= f.label "Genres in Database" %><br>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "Select Genre", selected: @song.genre ? @song.genre.id : nil } %><br>
    <%= f.label "Year Released" %>
    <%= f.text_field :year, maxlength: 4 %><br>
    <%= f.label "Number of Vocal Parts" %>
    <%= f.number_field :vocal_parts, in: 0..3, selected: @song.vocal_parts ? @song.vocal_parts : nil %><br>

    <%= f.submit %>

app/views/songs/_newform.html.erb
<div class="login-form">
    <%= form_with model: @song do |f| %>
    <%= render 'layouts/errors', object: @user %>
    <h2 class="text-center" style="color:rgb(0,0,0);">New User Registration</h2>   
    <div class="form-group">
    	<div class="input-group">
            <%= f.text_field(:username, placeholder: "User Name", class: "form-control", required: "required") %>
        </div>
    </div>
	<div class="form-group">
        <div class="input-group">
        	<%= f.password_field(:password, placeholder: "Password", class: "form-control", required: "required") %>			
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
        	<%= f.password_field(:password_confirmation, placeholder: "Confirm Password", class: "form-control", required: "required") %>			
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
        	<%= f.email_field(:email, placeholder: "Email Address", class: "form-control", required: "required") %>			
        </div>
    </div>          
    <div class="form-group">
        <%= f.submit "Sign Me Up!", class: "btn btn-dark", style: "color:rgb(0,0,0);font-weight:bold;" %>
    </div>
    <% end %>
</div>

app/views/songs/_player.html.erb
<iframe src="https://open.spotify.com/embed/track/<%= @song.spotify_id %>" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

app/views/songs/_rate.html.erb
<%= form_with model: @user_song, method: :patch, url: rate_song_path do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :song_id, :value => @song.id  %>
    <%= f.label :rating, "Your Rating"%>
    <%= f.number_field :rating, in: 1..5, placeholder: "Select from 1 (worst) to 5 (best)", style: "width:15em;" %>
    <%= f.submit "Update Rating" %>
<% end %> 

app/views/songs/_results.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody id="results">
    <tr>
    <% if @artists.present? %>
      <% @artists.each do |artist| %>
        <td><%= artist.name %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/_songbook.html.erb
<h1>Songs List, Sorted By Artist</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Genre</th>
        </tr>
    </thead>
    <tbody>
        <%= page_entries_info @songs %>
        <%= paginate @songs %>
        <% @songs.each do |song| %>
            <tr>
                <td><%= link_to song.full_title, artist_song_path(song.artist, song) %></td>
                <td><%= link_to song.artist.full_name, artist_path(song.artist) %></td>
                <td><%= link_to song.genre.name, song.genre %></td>
                <% if current_user %>
                    <% if !current_user.user_songs.where(song_id: song.id).exists? %>
                        <td><%= form_with model: @user_song, method: :post, url: add_song_path do |f|%>
                              
                                <%= f.hidden_field :user_id %>
                                <%= f.hidden_field :song_id, :value => song.id %>
                                <%= f.submit "Add song to collection" %></td>
                            <% end %>
                    <% else %>
                        <td>Song in collection</td>
                        <td><%= form_with model: @user_song, method: :delete, url: remove_song_path do |f| %>
                                <%= f.hidden_field :user_id %>
                                <%= f.hidden_field :song_id, :value => song.id %>
                                <%= f.submit "Remove song from collection", data: { confirm: 'Are you sure?' }  %></td>
                            <% end %>
                    <% end %>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @songs %>
<% if current_user %>
    <p>Quick Add an Entire Game's Setlist!</p>
    <p><%= render_game_button("Rock Band 1", 1) unless game_already_in_collection?(1) %></p>
    <p><%= render_game_button("Rock Band 2", 2) unless game_already_in_collection?(2) %></p>
    <p><%= render_game_button("Rock Band 3", 3) unless game_already_in_collection?(3) %></p>
    <p><%= render_game_button("Rock Band 4", 4) unless game_already_in_collection?(4) %></p>
    <p><%= render_game_button("LEGO: Rock Band", 51) unless game_already_in_collection?(51) %></p>
    <p><%= render_game_button("Green Day: Rock Band", 52) unless game_already_in_collection?(52) %></p>
    <p><%= render_game_button("Rock Band Blitz", 53) unless game_already_in_collection?(53) %></p>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song Details</h1>
<%= form_for [@song.artist, @song] do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/songs/index.html.erb
<h1>Songs List</h1>
<table>
    <thead>
        <tr>
            <th><%= link_to "Title", :sort => "name", class: "button" %></th>
            <th><%= link_to "Artist", :sort => "artist", class: "button" %></th>
            <th><%= link_to "Genre", :sort => "genre", class: "button" %></th>
            <% if current_user %>
                <th>Owned?</th>
                <th>Change Status</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <%= page_entries_info @songs %>
        <%= paginate @songs %> 
        <div class="sort-options"> 
            <%= link_to "Show only owned songs", :controller => "songs", :action => "index", :view => "owned" %> |
            <%= link_to "Show only unowned songs", :controller => "songs", :action => "index", :view => "unowned" %> | 
            <%= link_to "Reset Sorting", :controller => "songs", :action => "index", :view => "default" %>
        </div>
        <% @songs.each do |song| %>
            <tr>
                <td><%= link_to song.full_title, artist_song_path(song.artist, song) %></td>
                <td><%= link_to song.artist.full_name, artist_path(song.artist) %></td>
                <td><%= link_to song.genre.name, song.genre %></td>
                <% if current_user %>
                    <% if !current_user.user_songs.where(song_id: song.id).exists? %>
                        <td style="text-align:center;">No</td>
                        <td><%= form_with model: @user_song, method: :post, url: add_song_path do |f|%>
                                <%= f.hidden_field :user_id %>
                                <%= f.hidden_field :song_id, :value => song.id %>
                                <%= f.submit "Add song to collection" %></td>
                            <% end %>
                    <% else %>
                        <td style="text-align:center;">Yes</td>
                        <td><%= form_with model: @user_song, method: :delete, url: remove_song_path do |f| %>
                                <%= f.hidden_field :user_id %>
                                <%= f.hidden_field :song_id, :value => song.id %>
                                <%= f.submit "Remove song from collection", data: { confirm: 'Are you sure?' }  %></td>
                            <% end %>
                    <% end %>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @songs, window: 4 %>
<% if current_user %>
    <p>Quick Add an Entire Game's Setlist!</p>
    <p><%= render_game_button("Rock Band 1", 1) unless game_already_in_collection?(1) %></p>
    <p><%= render_game_button("Rock Band 2", 2) unless game_already_in_collection?(2) %></p>
    <p><%= render_game_button("Rock Band 3", 3) unless game_already_in_collection?(3) %></p>
    <p><%= render_game_button("Rock Band 4", 4) unless game_already_in_collection?(4) %></p>
    <p><%= render_game_button("LEGO: Rock Band", 51) unless game_already_in_collection?(51) %></p>
    <p><%= render_game_button("Green Day: Rock Band", 52) unless game_already_in_collection?(52) %></p>
    <p><%= render_game_button("Rock Band Blitz", 53) unless game_already_in_collection?(53) %></p>
<% end %>

app/views/songs/new.html.erb
<% if @song.artist %>
    <h1>Add a Song by <%= @song.artist.full_name %></h1>
<% else %>
    <h1>Add a Song</h1>
<% end %>
<%= form_for @song do |f| %>
    <%= render 'form', f: f %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.full_title %></h1> <br>
<h2>by: <%= @song.is_song_cover? %> <%= link_to @song.artist.full_name, artist_path(@song.artist) %></h2>
<%= display_album_art(@song) %>
<h3>From the album: <%= get_album_name(@song) %></h3>
<p>Average User Rating: 
    <% if @user_song.has_ratings? %>
        <%= @user_song.average_rating %> based on <%= @user_song.count_ratings %> ratings. </p><br>
    <% else %>
        There are no ratings for this song yet.<br>
    <% end %>
    <% if current_user && current_user.songs.exists?(@song.id)%>        
        <%= display_own_rating %>
        <%= render partial: 'rate' %>
    <% else %>
        You can rate this song if you are signed in and you own it.
    <% end %></p>
<p>Genre: <%= link_to @song.genre.name, genre_path(@song.genre) %></p>
<p>Year Released: <%= @song.year %></p>
<p>Song Length: <%= @song.duration ? @song.length_in_minutes : "Not Provided" %></p>
<p>Harmonies?: <%= @song.harmony_parts? %></p>
<p>Source: <%= @song.primary_source %></p>
<%= render partial: 'player', locals: {song: @song} %> <br>

<% if current_user %>
    <% if current_user.songs.exists?(@song.id) %>
        <p>You currently own this song</p>
    <% else %>
        <p>You do not currently own this song</p>
    <% end %>
<% else %>
    <p>Sign Up or Log In to track your songs!</p>
<% end %>

<%= edit_button_for_admin %><br>
<%= destroy_button_for_admin %>
<% if current_user %>
<%= form_with model: @user_song, method: :post, url: add_song_path do |f|%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :song_id, :value => @song.id %>
    <%= f.submit "Add song to collection" %></td>
<% end %>
<% end %>