config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  resources :artists do
    resources :songs, only: [:show, :new, :create, :edit, :update, :destroy]
    # get '/songs/:artist_id/:song_id', to: 'songs#show', as: 'artist_song' 
    # get '/artists/:artist_id', to: 'artists#show', as: 'artist'
    # saving these for after the project review since i don't want to use restful urls. those are dumb.
  end
  resources :songs, only: [:index, :new, :create]
  resources :genres, only: [:index, :show]
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users', to: 'users#index', as: 'users'
  get '/users/username', to: 'users#username', as: 'username'
  patch '/users/:id', to: 'users#create_username'
  post '/users', to: 'users#create'
  get '/users/:username', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:username/toggle', to: 'users#toggle_party', as: 'toggle_party'
  get '/search', to: 'search#show', as: 'search_page'
  post '/usersongs', to: 'user_songs#create', as: 'add_song'
  post '/usersongs/game', to: 'user_songs#add_game', as: 'add_game' 
  patch '/usersongs', to: 'user_songs#rate_song', as: 'rate_song'
  delete '/usersongs', to: 'user_songs#destroy', as: 'remove_song'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'
  namespace :party do
    root 'static#party'
    get '/:username/playlist', to: 'playlists#index', as: 'playlist'
    get '/:username', to: 'hosts#show'
    get '/:username/playlist/edit', to: 'playlists#edit'
    get '/:username/history', to: 'histories#show', as: 'user_history'
    patch '/:username', to: 'hosts#update'
    delete '/:username', to: 'hosts#destroy'
    get '/:username/guests', to: 'guests#index', as: 'guests_home'
    get '/:username/guests/new', to: 'guests#new', as: 'guests_add_song'
    delete '/guests', to: 'guests#destroy', as: 'clear_song'
    get '/histories', to: 'histories#index'
    get '/:username/add-song', to: 'guests#new'
    post '/:username', to: 'guests#create'
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id = "error_explanation">
    <div class = "alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>

<html>
	<head>
		<title>Rock Band Night</title>
		<%= csrf_meta_tags %>
    	<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	</head>
	<body class="homepage is-preload">
		<script>
			function dropMenu() {
  				document.getElementById("myDropdown").classList.toggle("show");
			}
			window.onclick = function(event) {
  				if (!event.target.matches('.dropbtn')) {
    				var dropdowns = document.getElementsByClassName("dropdown-content");
    				var i;
    				for (i = 0; i < dropdowns.length; i++) {
	      				var openDropdown = dropdowns[i];
      					if (openDropdown.classList.contains('show')) {
        					openDropdown.classList.remove('show');
      					}		
    				}
  				}
			}
		</script>
		<div id="page-wrapper">
			<% if current_user && current_user.party_enabled == true %>
				<div id="party-header-wrapper">
			<% else %>
				<div id="header-wrapper">
			<% end %>
				<div id="header" class="container">
					<h1 id="logo"><%= link_to "Rock Band Night", root_path %></h1>
					<nav id="nav">
						<ul>
							<li>
								<div class="dropdown">
									<button 
										class="dropbtn"
										type="button"
										aria-expanded="false"
										onclick="dropMenu()"
										>
										Main Menu
									</button>
									<div id="myDropdown" class="dropdown-content">
									    <% if !current_user %>
											<%= link_to "Sign Up", new_user_path %>
    	    								<%= link_to "Sign In", signin_path %>
										<% else %>
        									<%= link_to "My Profile", user_path(current_user.username) %>
											<% if current_user == User.find(1) %>
												<%= link_to "New Song", new_song_path %>
											<% end %>
        									<%= link_to "Log Out", logout_path, method: :delete %>
										<% end %>
									</div>
								</div>
							</li>
							<li><%= link_to "Songs", songs_path %></li>
							<li class="break"><%= link_to "Artists", artists_path %></li>
							<% if current_user %>
								<% if current_user.party_enabled == false %>
									<li><%= link_to "Start Party Mode", toggle_party_path(current_user.username) %></li>
								<% else %>
									<li><%= link_to "End Party Mode", toggle_party_path(current_user.username) %></li>
								<% end %>
							<% else %>
								Party Mode Unavailable
							<% end %>
							<% unless current_user && current_user.party_enabled == true %>
								<%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
  									<div class="input-group" style="display:einline;">  
    									<%= search_field_tag :search, params[:search], placeholder: "Search Songs", class: "form-control" %>  
    									<input type='submit' name='Search'>
									</div>  
								<% end %>
							<% end %>
						</ul>
					</nav>
				</div>
				<div class="wrapper">
          			<% flash.each do |type, msg| %>
  						<div>
    						<%= msg %>
  						</div>
					<% end %>
					<% if current_page?(root_path) %>
					<section id="hero" class="container">
						<header>
							<h2>Welcome to Rock Band Night
							<br />
							For Smoother Rocking Sessions!</h2>
						</header>
						<% if !current_user %>
							<%= render 'sessions/form' %>
						<% end %>
					</section>
					<% end %>
					<%= yield %>
				</div>
				<div id="footer-wrapper">
					<div id="footer" class="container">
						<header class="major">
							<h2>Last Updated:</h2>
							<p>Initial</p>
						</header>
					</div>
				<div id="copyright" class="container">
					<ul class="menu">
						<li><small><strong>This site is neither operated nor sponsored by Harmonix Music Systems, Inc. Rock Band and all related titles and logos are trademarks of Harmonix Music Systems, Inc. All rights reserved.</strong><br></li>
        				<li><small><strong>ALL OTHER LOGOS, COMPANY NAMES, BRANDS, IMAGES, TRADEMARKS AND OTHER INTELLECTUAL PROPERTY ARE THE PROPERTY OF THEIR RESPECTIVE OWNERS.</strong></a></li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>